In [199]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

In [200]:
df = pd.read_csv("ANZ.csv")

In [201]:
df_salaries = df[df["txn_description"]=="PAY/SALARY"].groupby("customer_id").mean()

In [202]:
salary = []

for customer_id in df["customer_id"]:
    salary.append(int(df_salaries.loc[customer_id]["amount"]))

df["annual_salary"] =  salary

In [203]:
df.shape

(12043, 24)

In [204]:
df=df[['card_present_flag','amount', 'balance', 'age', 'annual_salary']]

In [205]:
df=df[['amount', 'balance', 'age', 'annual_salary']]

In [206]:
df

amount   balance  age  annual_salary
0       16.25     35.39   26           1013
1       14.19     21.20   26           1013
2        6.42      5.71   38           1002
3       40.90   2117.22   40            892
4        3.25     17.95   26           1013
...       ...       ...  ...            ...
12038    9.79  14054.14   30           1636
12039   63.87   9137.79   20           2320
12040   43.96  45394.57   28           4054
12041   30.77  11350.67   69           1043
12042   22.36   5517.91   31            996

[12043 rows x 4 columns]

In [207]:
#Create Feature Matrix and Dependent Variable Vector
X = df.iloc[:, :-1].values
y = df.iloc[:, 3].values

In [208]:
X

array([[1.625000e+01, 3.539000e+01, 2.600000e+01],
       [1.419000e+01, 2.120000e+01, 2.600000e+01],
       [6.420000e+00, 5.710000e+00, 3.800000e+01],
       ...,
       [4.396000e+01, 4.539457e+04, 2.800000e+01],
       [3.077000e+01, 1.135067e+04, 6.900000e+01],
       [2.236000e+01, 5.517910e+03, 3.100000e+01]])

In [209]:
y

array([1013, 1013, 1002, ..., 4054, 1043,  996])

In [210]:
#Split the data into training and test datasets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [211]:
len(X_train)

8430

In [212]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
MLR = LinearRegression()
MLR.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [213]:
#Print the constant and coeffcients
print(f'intercept = {MLR.intercept_}')
print(f'coefficients = {MLR.coef_}')

intercept = 2713.976164837694
coefficients = [ 1.18799943e-01  1.23568541e-02 -2.04595657e+01]


In [214]:
# Predicting the Test set results
y_predict = MLR.predict(X_test)
y_predict

array([2312.69041267, 2519.70870039, 2426.20314516, ..., 2652.95621603,
       2212.16096153, 2452.11989063])

In [215]:
# Display actual and predicted values side by side
df = pd.DataFrame(data=y_test, columns=['y_test'])
df['y_predict'] = y_predict
df

y_test    y_predict
0       1037  2312.690413
1       1099  2519.708700
2        761  2426.203145
3       1808  2150.940520
4       2320  2398.494054
...      ...          ...
3608    1396  2209.521558
3609    2500  2050.700016
3610    4054  2652.956216
3611     664  2212.160962
3612    6024  2452.119891

[3613 rows x 2 columns]

In [216]:
#Model Evaluation using R-Square
from sklearn import metrics
r_square = metrics.r2_score(y_test, y_predict)
print('R-Square Error:', r_square)
print("MSE",np.sqrt(mean_squared_error(y_test,y_predict)))

R-Square Error: 0.09164599455928768
MSE 1336.1595937272043


In [217]:
n = 12043
p = 5
Adj_r_square = 1-(1-r_square)*(n-1)/(n-p-1)
print('Adjusted R-Square Error:', Adj_r_square)

Adjusted R-Square Error: 0.0912686771191279
